version: '3'
services:
   zookeeper:
     image: zookeeper:3.4.11
     ports:
       - "2181:2181"
       - "2888:2888"
       - "3888:3888"

   kafka:
     image: wurstmeister/kafka:1.0.0
     ports:
       - "9092:9092"
     environment:
       KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

   kafka-manager:
     image: sheepkiller/kafka-manager
     ports:
       - "9000:9000"
     links:
       - kafka
       - zookeeper
     environment:
       APPLICATION_SECRET: 123456
       ZK_HOSTS: zookeeper:2181

   db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: example
     ports:
        - 5432:5432

   adminer:
     image: adminer
     restart: always
     ports:
       - 8085:8080