spring:
    profiles.active: dev
---
spring:
    profiles: dev
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: example
        max-active: 8
        max-idle: 4
    kafka:
        bootstrap-servers: localhost:9092
        topic:
          producttopic: producttopictest.t